--------------------------------------------------------
--  DDL for Table ATTENDEES
--------------------------------------------------------

  CREATE TABLE "CNC"."ATTENDEES" 
   (	"PK" NUMBER, 
	"NAME" VARCHAR2(100 BYTE), 
	"COMPANY" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"TWITTER" VARCHAR2(50 BYTE), 
	"IMAGE" CLOB, 
	"IMAGE_THUMB" CLOB, 
	"IMAGE_MORPH" CLOB, 
	"IMAGE_ASSOC" CLOB, 
	"CNC_PATH" VARCHAR2(2000 BYTE), 
	"REQUESTED_COUNT" NUMBER, 
	"CREATED_DATE" TIMESTAMP (6) DEFAULT systimestamp, 
	"LAST_REQUESTED_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("IMAGE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("IMAGE_THUMB") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("IMAGE_MORPH") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("IMAGE_ASSOC") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Index ATTENDEES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CNC"."ATTENDEES_PK" ON "CNC"."ATTENDEES" ("PK") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ATTENDEES
--------------------------------------------------------

  ALTER TABLE "CNC"."ATTENDEES" MODIFY ("PK" NOT NULL ENABLE);
  ALTER TABLE "CNC"."ATTENDEES" MODIFY ("REQUESTED_COUNT" NOT NULL ENABLE);
  ALTER TABLE "CNC"."ATTENDEES" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "CNC"."ATTENDEES" ADD CONSTRAINT "ATTENDEES_PK" PRIMARY KEY ("PK")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  DDL for Trigger CNC_INSERT_PK
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "CNC"."CNC_INSERT_PK" 
BEFORE INSERT ON ATTENDEES 
REFERENCING OLD AS OLD NEW AS NEW 
FOR EACH ROW
BEGIN
  SELECT SEQ_CNC.nextval
  INTO :NEW.PK
  FROM dual;
  
  SELECT 0 
  INTO :NEW.REQUESTED_COUNT 
  FROM DUAL;
  
   SELECT SYSTIMESTAMP
  INTO :NEW.CREATED_DATE
  FROM DUAL;
  
END;
/
ALTER TRIGGER "CNC"."CNC_INSERT_PK" ENABLE;
